---
# /*
#  * Copyright (c) 2021 Software AG, Darmstadt, Germany and/or its licensors
#  *
#  * SPDX-License-Identifier: Apache-2.0
#  *
#  *   Licensed under the Apache License, Version 2.0 (the "License");
#  *   you may not use this file except in compliance with the License.
#  *   You may obtain a copy of the License at
#  *
#  *       http://www.apache.org/licenses/LICENSE-2.0
#  *
#  *   Unless required by applicable law or agreed to in writing, software
#  *   distributed under the License is distributed on an "AS IS" BASIS,
#  *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  *   See the License for the specific language governing permissions and
#  *   limitations under the License.
#  *
#  */

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "apigateway.customPrefix" . }}{{ .Values.global.app }}-ingress
  labels:
    {{- include "apigateway.labels" . | nindent 4 }}
  annotations:                                    
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  rules:
  - host: {{ .Values.global.app }}-rt-{{ .Release.Namespace }}{{ .Values.k8sClusterSuffix }}
    http:
      paths:
      - backend:
          serviceName: {{ include "apigateway.customPrefix" . }}{{ .Values.externalLoadBalancer | ternary .Values.nginxService .Values.apigwRtService }}
          servicePort: {{ int .Values.apigwRuntimePort }}
        path: /
  - host: {{ .Values.global.app }}-ui-{{ .Release.Namespace }}{{ .Values.k8sClusterSuffix }}
    http:
      paths:
      - backend:
          serviceName: {{ include "apigateway.customPrefix" . }}{{ .Values.externalLoadBalancer | ternary .Values.nginxService .Values.apigwUiService }}
          servicePort: {{ int .Values.apigwUiPort }}
        path: /