---
# /*
#  * Copyright (c) 2021 Software AG, Darmstadt, Germany and/or its licensors
#  *
#  * SPDX-License-Identifier: Apache-2.0
#  *
#  *   Licensed under the Apache License, Version 2.0 (the "License");
#  *   you may not use this file except in compliance with the License.
#  *   You may obtain a copy of the License at
#  *
#  *       http://www.apache.org/licenses/LICENSE-2.0
#  *
#  *   Unless required by applicable law or agreed to in writing, software
#  *   distributed under the License is distributed on an "AS IS" BASIS,
#  *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  *   See the License for the specific language governing permissions and
#  *   limitations under the License.
#  *
#  */

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apigateway.customPrefix" . }}{{ .Values.apigwConfigmap }}
  labels:
    {{- include "apigateway.labels" . | nindent 4 }}

data:
  config-sources.yml: |
    sources:
    - type: YAML
      allowEdit: false
      properties:
        location: elasticsearch.yml
    - type: YAML
      allowEdit: false
      properties:
        location: ignite-settings.yml
       
  elasticsearch.yml: |
    apigw:
      elasticsearch:
        hosts: {{ include "apigateway.customPrefix" . }}{{ .Values.elasticsearchkibana.elasticSearchService }}:{{ int .Values.elasticsearchkibana.elasticSearchPort }}
        autostart: false
      kibana:
        dashboardInstance: http://{{ include "apigateway.customPrefix" . }}{{ .Values.elasticsearchkibana.kibanaService }}:{{ .Values.elasticsearchkibana.kibanaPort }}
        autostart: false
       
  ignite-settings.yml: |
    apigw:
      cluster:
        aware: true
        name:  IgniteCluster
        sessTimeout: 60
        actionOnStartupError:  standalone
        ignite:
          k8sServiceName: {{ include "apigateway.customPrefix" . }}{{ .Values.apigwUiService }}
          k8sNamespace:   {{ .Release.Namespace }}
          discoveryPort:     10100
          communicationPort: 10400